FROM node:18-alpine AS builder

WORKDIR /app

ENV NODE_ENV=development

COPY package.json ./package.json

COPY tsconfig.json ./tsconfig.json

COPY src/bot ./src/

RUN npm i

RUN npm run build

FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app/dist ./dist/

COPY ./package.bot.json ./package.json

RUN npm i --production

EXPOSE $PORT

CMD ["npm", "start"]




#FROM node:18-alpine
#
#WORKDIR /app
#
#COPY  src/bot ./dist/bot/
#
#COPY  package.json .
#
#RUN npm i --production
#
#CMD ["npm", "run", "start:bot"]
